CREATE TABLE analyzed_emotion (
    analyzed_emotion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_capsule_id BIGINT NOT NULL,
    analyzed_emotion TEXT NOT NULL,
    percentage INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analyzed_feedback (
    analyzed_feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_capsule_id BIGINT NOT NULL,
    analyzed_feedback TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat (
    chat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatroom_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    sender VARCHAR(10) NOT NULL,
    chat_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chatrooms (
    chatroom_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    is_ended BOOLEAN NOT NULL DEFAULT FALSE,
    first_chat_time TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_temp_save BOOLEAN NOT NULL DEFAULT FALSE,
    gauge INTEGER NULL
);

CREATE TABLE emotion_variation (
    emotion_variation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    time TIMESTAMP NOT NULL,
    label VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE keywords (
    keyword_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    report_id BIGINT NOT NULL
);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    type VARCHAR(30) NOT NULL,
    target_id BIGINT NULL,
    arrived_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_date DATE NOT NULL,
    today_summary TEXT NOT NULL,
    stress_index INTEGER NOT NULL,
    happiness_index INTEGER NOT NULL,
    emotion_summary TEXT NOT NULL,
    is_opened BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE time_capsules (
    time_capsule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    report_id BIGINT NULL,
    chatroom_id BIGINT NOT NULL,
    history_date TIMESTAMP NOT NULL,
    one_line_summary TEXT NOT NULL,
    dialogue_summary TEXT NOT NULL,
    my_mind_note TEXT NULL,
    favorite_at TIMESTAMP NULL,
    opened_at TIMESTAMP NULL,
    is_opened BOOLEAN NOT NULL DEFAULT FALSE,
    is_temp_save BOOLEAN NOT NULL DEFAULT FALSE,
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_type VARCHAR(20) NOT NULL,
    social_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NULL,
    profile_image_url TEXT NULL,
    nickname VARCHAR(255) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    birthday DATE NOT NULL,
    key_count BIGINT NOT NULL DEFAULT 0,
    ticket_count BIGINT NOT NULL DEFAULT 0,
    is_terms_agreed BOOLEAN NOT NULL DEFAULT FALSE,
    is_privacy_agreed BOOLEAN NOT NULL DEFAULT FALSE,
    is_marketing_agreed BOOLEAN NOT NULL DEFAULT FALSE,
    app_push_notify BOOLEAN NOT NULL DEFAULT TRUE,
    emotion_reminder_notify BOOLEAN NOT NULL DEFAULT TRUE,
    emotion_reminder_time TIME NULL,
    time_capsule_report_notify BOOLEAN NOT NULL DEFAULT TRUE,
    marketing_info_notify BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attendance_streak INTEGER NOT NULL DEFAULT 0,
    last_attendance_reward_date DATE NULL,
    CONSTRAINT uk_users_email_deleted_at UNIQUE (email, deleted_at)
);

CREATE TABLE user_emotion_reminder_days (
    user_id BIGINT NOT NULL,
    emotion_reminder_day VARCHAR(20) NOT NULL,
    CONSTRAINT user_emotion_reminder_days_ibfk_1
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE user_expectations (
    user_id BIGINT NOT NULL,
    expectation VARCHAR(100) NOT NULL,
    CONSTRAINT user_expectations_ibfk_1
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_user_emotion_reminder_days_user_id ON user_emotion_reminder_days (user_id);
CREATE INDEX idx_user_expectations_user_id ON user_expectations (user_id);
