name: CI - Build and Store Artifacts

on:
  push:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Make zip file
        run: |
          cp appspec.yml ./deploy/
          cp -r scripts ./deploy/
          cd deploy
          zip -r ../mooi-server-${{ github.run_number }}.zip .
          cd ..
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./mooi-server-${{ github.run_number }}.zip s3://${{ vars.S3_BUCKET_NAME }}/
          echo "Artifact uploaded: mooi-server-${{ github.run_number }}.zip"

      - name: Create Release Info
        run: |
          cat > release-info.json << EOF
          {
            "version": "${{ github.run_number }}",
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "commit_message": "${{ github.event.head_commit.message }}",
            "artifact_key": "mooi-server-${{ github.run_number }}.zip",
            "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "workflow_run_id": "${{ github.run_id }}",
            "build_status": "success"
          }
          EOF

      - name: Store Release Info
        run: |
          aws s3 cp --region ap-northeast-2 release-info.json s3://${{ vars.S3_BUCKET_NAME }}/releases/release-${{ github.run_number }}.json

      - name: Notify CI completion
        run: |
          echo "✅ CI completed successfully!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Build Number: ${{ github.run_number }}"
          echo "Artifact: mooi-server-${{ github.run_number }}.zip"
          echo "Release Info: s3://${{ vars.S3_BUCKET_NAME }}/releases/release-${{ github.run_number }}.json"
          echo "Ready for manual deployment!"
